exclude_type_vars: &exclude_type_vars
  - js
  - tsx
  - ts
  - md
  - ini
  - json
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
        exclude_type_vars: *exclude_type_vars
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
        args:
          - -i
          - column_limit = 88
          - based_on_style = "google"
          - split_before_logical_operator = true
          - split_before_arithmetic_operator = true
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff
        args:
          - --fix
