FROM python:3.11

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_CREATE=false

RUN pip install poetry

WORKDIR /usr/src/app

COPY pyproject.toml .
COPY poetry.lock .

RUN poetry install --without dev --no-root --no-directory

COPY . .

CMD ["uvicorn", "app.main:app", "--host=0.0.0.0", "--loop=uvloop", "--port=5000"]
